language: php
php:
  - 7.3.2

install:
  - travis_retry composer install --no-interaction --no-suggest

script:
  - composer test -- -c phpunit.dist.xml

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache
